default:
  ALLOWED_HOSTS: [ ]
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .static
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
    - scripts
    - src/project/static
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES:
    - src/applications/blog/templates/
    - src/applications/hello/templates/
    - src/applications/landing/templates/
    - src/applications/onboarding/templates/
    - src/project/templates/
  MODE_DEBUG: true
  HOST: ""
  MODE_PROFILING: false
  PORT: -1
  SECRET_KEY: ""
  SENTRY_DSN: ""
  PROJECT_NAME: "kol4"
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  PORT: 8000
  HOST: "localhost"
  SECRET_KEY: "1"

ci:
  HOST: "localhost"
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2

heroku:
  HOST: "kol4sew.herokuapp.com"
  MODE_DEBUG: false


